devpro/devpro/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^propage/', include('propage.urls')),
    url(r'^ivi/', include('ivi.urls')),
    url(r'^zan/', include('zan.urls')),

    url(r'^admin/', admin.site.urls),
]

devpro/ivi/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

devpro/propage/urls.py
from django.conf.urls import url

from . import views

app_name = 'propage'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^ivi/$', views.IviView, name='ivi'),
    url(r'^ivi/about/$', views.About, name='about'),
    url(r'^ivi/game_rab/$', views.Game_rab, name='game_rab'),


]

devpro/zan/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

devpro/ivi/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

devpro/propage/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import datetime
"""projex == projects"""

class Projex(models.Model):
    title_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.title_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now



class Choice(models.Model):
    question = models.ForeignKey(Projex, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

devpro/zan/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

devpro/ivi/views.py
from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello, world. You're at the ivi Page index")

devpro/propage/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect

import datetime

from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404


from .models import Projex, Choice

from django.views import generic

class IndexView(generic.ListView):
    template_name = 'propage/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Projex.objects.order_by('-pub_date')[:5]


def detail(request, question_id):
    try:
        question = Projex.objects.get(pk=question_id)
    except Projex.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'propage/developer_bio.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Projex, pk=question_id)
    return render(request, 'propage/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Projex, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'propage/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('propage:results', args=(question.id,)))


def current_datetime(request):
    now = datetime.datetime.now()

    html = "<html><body>It is now %s.</body></html>" % now

    return HttpResponse(html)




def IviView(request):
    return render(request, 'propage/bootstrap_test.html')


def About(request):
    return render(request, 'propage/about.html')

def Game_rab(request):
    return render(request, 'propage/rollaball_web/roll_a_ball.html')

devpro/zan/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at the zan Page index")

devpro/propage/templates/propage/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible"
          content="IE=edge">
    <meta name="viewport"
          content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description"
          content="">
    <meta name="author"
          content="">

    <link rel="icon"
          href="../../favicon.ico">

    <title>About iVi</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    {% load static %}

    <link href="{% static 'propage/carousel.css' %}"
          rel="stylesheet">
</head>
<!-- NAVBAR
================================================== -->
<body>
<div class="navbar-wrapper">
    <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button"
                            class="navbar-toggle collapsed"
                            data-toggle="collapse"
                            data-target="#navbar"
                            aria-expanded="false"
                            aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand"
                       href="#">iVi</a>
                </div>
                <div id="navbar"
                     class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'propage:ivi' %}">Home</a></li>
                        <li class="active"><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>

                        <!-- Hidden drop down menu for future use-->
                        <li class="dropdown"
                            style="display:none;">
                            <a href="#"
                               class="dropdown-toggle"
                               data-toggle="dropdown"
                               role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator"
                                    class="divider"></li>
                                <li class="dropdown-header">Nav header</li>
                                <li><a href="#">Separated link</a></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </div>
<div class="container">

      <div class="starter-template">
        <h1>The iVi Project</h1>
        <p class="lead">The iVi project was spawned by a group of engineers to build creative and bold designs.<br>
        A group of engineers teamed up to build games and works of art. After careful planning and preparation for
            three years, they finally started building software projects.
        </p>
      </div>

    </div>

 <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2016 iVi &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
 </footer>
</div>
       <!-- FOOTER -->



<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</body>
</html>

devpro/propage/templates/propage/bootstrap_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible"
          content="IE=edge">
    <meta name="viewport"
          content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description"
          content="">
    <meta name="author"
          content="">

    <link rel="icon"
          href="../../favicon.ico">

    <title>iVi</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    {% load static %}

    <link href="{% static 'propage/carousel.css' %}"
          rel="stylesheet">
</head>
<!-- NAVBAR
================================================== -->
<body>
<div class="navbar-wrapper">
    <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button"
                            class="navbar-toggle collapsed"
                            data-toggle="collapse"
                            data-target="#navbar"
                            aria-expanded="false"
                            aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand"
                       href="#">iVi</a>
                </div>
                <div id="navbar"
                     class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'propage:ivi' %}">Home</a></li>
                        <li><a href="{% url 'propage:about' %}">About</a></li>
                        <li><a href="#contact">Contact</a></li>

                        <!-- Hidden drop down menu for future use-->
                        <li class="dropdown" style="display:none;">
                            <a href="#"
                               class="dropdown-toggle"
                               data-toggle="dropdown"
                               role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator"
                                    class="divider"></li>
                                <li class="dropdown-header">Nav header</li>
                                <li><a href="#">Separated link</a></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </div>
</div>


<!-- Carousel
================================================== -->
<div id="myCarousel"
     class="carousel slide"
     data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel"
            data-slide-to="0"
            class="active"></li>
    </ol>
    <div class="carousel-inner"
         role="listbox">
        <div class="item active">
            <img class="first-slide"
                 src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                 alt="First slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Beginner's Sphere</h1>
                    <p>A roll a ball game developed from Unity's game engine and a result of the first tutorial.
                        Enjoy the 3D effects and not-so-BREATHTAKING simulation!</p>
                    <p><a class="btn btn-lg btn-primary"
                          href="{% url 'propage:game_rab' %}"
                          role="button">Play now!</a></p>
                </div>
            </div>
        </div>
    </div>
    <a class="left carousel-control"
       href="#myCarousel"
       role="button"
       data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"
              aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control"
       href="#myCarousel"
       role="button"
       data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"
              aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div><!-- /.carousel -->



    <!-- /END THE FEATURETTES -->

<div>
    <!-- FOOTER -->
    <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2016 iVi &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>

</div><!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

devpro/propage/templates/propage/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>App page</title>
</head>
<body>
    <h1>{{ question.title_text }}</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'propage:vote' question.id %}" method="post">

        {% csrf_token %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
        <input type="submit" value="Vote" />
    </form>
</body>
</html>

devpro/propage/templates/propage/developer_bio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible"
          content="IE=edge">
    <meta name="viewport"
          content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description"
          content="">
    <meta name="author"
          content="">
    <link rel="icon"
          href="../../favicon.ico">

    <title>Cover Template for Bootstrap</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->
    {% load static %}
    <link href="{% static 'propage/cover.css' %}"
          rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>


    </style>
</head>

<body>

<div class="site-wrapper">


    <div class="site-wrapper-inner">

        <div class="cover-container">

            <div class="masthead clearfix">
                <div class="inner">
                    <h3 class="masthead-brand">MindStorm</h3>
                    <nav>
                        <ul class="nav masthead-nav">
                            <li class="active"><a href="#">Home</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </nav>
                </div>
            </div>

            <div class="inner cover">
                <h1 class="cover-heading">Creativity starts here</h1>
                <p class="lead">MindStorm is a software developer who loves to work on projects that challenge
                    design norms and create beautiful works of Engineering Art</p>
                <p class="lead">
                    <a href="#"
                       class="btn btn-lg btn-default">Zan</a>
                    <a href="{% url 'propage:ivi' %}"
                       class="btn btn-lg btn-default">iVi</a>
                </p>
            </div>

            <div class="mastfoot">
                <div class="inner">
                    <p>© 2016 MindStorm, All Rights Reserved.</p>
                </div>
            </div>

        </div>

    </div>

</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</body>
</html>

devpro/propage/templates/propage/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'propage/style.css' %}" />
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Developers Bio</title>
</head>
<body>
    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'propage:detail' question.id %}">{{ question.title_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

devpro/propage/templates/propage/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

<a href="{% url 'propage:detail' question.id %}">Vote again?</a>
</body>
</html>

devpro/propage/templates/propage/rollaball_web/roll_a_ball.html
<!doctype html>
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type"
          content="text/html; charset=utf-8">
    <title>Unity WebGL Player | Roll a ball</title>
    <link rel="stylesheet"
          href="TemplateData/style.css">
    <link rel="shortcut icon"
          href="TemplateData/favicon.ico"/>
    <script src="TemplateData/UnityProgress.js"></script>
</head>
<body class="template">
<p class="header"><span>Unity WebGL Player | </span>Roll a ball</p>
<div class="template-wrap clear">
    <canvas class="emscripten"
            id="canvas"
            oncontextmenu="event.preventDefault()"
            height="600px"
            width="960px"></canvas>
    <br>
    <div class="logo"></div>
    <div class="fullscreen"><img src="TemplateData/fullscreen.png"
                                 width="38"
                                 height="38"
                                 alt="Fullscreen"
                                 title="Fullscreen"
                                 onclick="SetFullscreen(1);"/></div>
    <div class="title">Roll a ball</div>
</div>
<p class="footer">&laquo; created with <a href="http://unity3d.com/"
                                          title="Go to unity3d.com">Unity</a> &raquo;</p>
<script type='text/javascript'>
  var Module = {
    TOTAL_MEMORY: 268435456,
    errorhandler: null,			// arguments: err, url, line. This function must return 'true' if the error is handled, otherwise 'false'
    compatibilitycheck: null,



    dataUrl: "Release/rollaball_web.data",
    codeUrl: "Release/rollaball_web.js",
    memUrl: "Release/rollaball_web.mem",
  };

</script>
<script src="Release/UnityLoader.js"></script>

</body>
</html>